
package com.kthree.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HandlerTestService", targetNamespace = "http://HandlerTestService.org/wsdl", wsdlLocation = "file:/C:/Raja/Projects/Learn/eclipse-workspace/handlers/src/main/resources/wsdl/HandlerTestService.wsdl")
@HandlerChain(file = "HandlerTestService_handler.xml")
public class HandlerTestService
    extends Service
{

    private final static URL HANDLERTESTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Raja/Projects/Learn/eclipse-workspace/handlers/src/main/resources/wsdl/HandlerTestService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HANDLERTESTSERVICE_WSDL_LOCATION = url;
    }

    public HandlerTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HandlerTestService() {
        super(HANDLERTESTSERVICE_WSDL_LOCATION, new QName("http://HandlerTestService.org/wsdl", "HandlerTestService"));
    }

    /**
     * 
     * @return
     *     returns HandlerPortType
     */
    @WebEndpoint(name = "HandlerPort")
    public HandlerPortType getHandlerPort() {
        return (HandlerPortType)super.getPort(new QName("http://HandlerTestService.org/wsdl", "HandlerPort"), HandlerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HandlerPortType
     */
    @WebEndpoint(name = "HandlerPort")
    public HandlerPortType getHandlerPort(WebServiceFeature... features) {
        return (HandlerPortType)super.getPort(new QName("http://HandlerTestService.org/wsdl", "HandlerPort"), HandlerPortType.class, features);
    }

}
